#!/usr/bin/env bash
# build-libriscv.sh <out-dir>
#
# libriscv -> wasm32, with our blinkenlib-shaped C API. PROVEN: this exact
# sequence drives RV64GC -- add=12, loop=55, auipc=0x1122334455667788.
# See docs/libriscv-riscv64.md.
set -euo pipefail
OUT="${1:?}"; mkdir -p "$OUT"
HERE="$(cd "$(dirname "$0")" && pwd)"
. "$HERE/pins.env"
D="$HOME/libriscv-src"

if [ ! -d "$D" ]; then
  git clone https://github.com/libriscv/libriscv.git "$D" >/dev/null 2>&1
fi
git -C "$D" checkout -q "$LIBRISCV_COMMIT"
echo "## libriscv pinned at $(git -C "$D" rev-parse --short HEAD)"
. "$EMSDK/emsdk_env.sh" >/dev/null 2>&1 || true

W="$D/examples/wasm"
cp "$HERE/gx_rv.cpp" "$W/gx_rv.cpp"

# Build our target ALONGSIDE their wasm_example, in THEIR tree. Three reasons,
# each learned the expensive way:
#   - add_subdirectory(../../lib libriscv) in their CMakeLists is RELATIVE, so
#     copying examples/wasm elsewhere breaks configure;
#   - their CMAKE_CXX_FLAGS already carry -fexceptions, which MUST be on the
#     compile step or libriscv's ELF loader throw dies as "table index is out of
#     bounds" inside an invoke_* trampoline;
#   - libriscv_settings.h is GENERATED by their CMake, so a hand-rolled emcc
#     cannot see it.
grep -q "gx_rv" "$W/CMakeLists.txt" || cat >> "$W/CMakeLists.txt" <<'EOF'

add_executable(gx_rv gx_rv.cpp)
target_link_libraries(gx_rv PRIVATE riscv)
set_target_properties(gx_rv PROPERTIES CXX_STANDARD 20 CXX_STANDARD_REQUIRED ON SUFFIX ".mjs")
target_link_options(gx_rv PRIVATE
  "-sEXPORTED_FUNCTIONS=['_gx_load_elf','_gx_init','_gx_reset','_gx_read_x','_gx_write_x','_gx_set_pc','_gx_get_pc','_gx_step','_gx_sym','_gx_ptr_bytes','_gx_icount','_malloc','_free']"
  "-sEXPORTED_RUNTIME_METHODS=['ccall','cwrap','HEAPU8']"
  "-sMODULARIZE=1" "-sEXPORT_ES6=1" "-sENVIRONMENT=web,worker,node" "-sASSERTIONS=1")
EOF

B="$W/.build"
rm -rf "$B" && mkdir -p "$B" && cd "$B"
# Their build.sh is STALE -- it passes -DCMAKE_TOOLCHAIN_FILE=../cmake/wasm.cmake
# and that path does not exist in the repo. emcmake is what works. Their OPTIONS
# remain the source of truth.
#
# RISCV_EXT_C=ON IS MANDATORY. Their example ships OFF, and -march=rv64gc
# compresses AUTOMATICALLY -- so with OFF, libriscv REJECTS our ELFs at LOAD
# (gx_load_elf -> -1), not at execution. Do not "simplify" this to their default.
#
# RISCV_BINARY_TRANSLATION=OFF: the translator dispatches through indirect calls,
# which cannot exist in wasm.
emcmake cmake -DCMAKE_BUILD_TYPE=Release \
  -DRISCV_32I=OFF -DRISCV_64I=ON \
  -DRISCV_EXT_C=ON -DRISCV_EXT_V=OFF \
  -DRISCV_MEMORY_TRAPS=OFF \
  -DRISCV_BINARY_TRANSLATION=OFF \
  -DRISCV_EXPERIMENTAL=ON \
  -DRISCV_ENCOMPASSING_ARENA=ON -DRISCV_ENCOMPASSING_ARENA_BITS=28 \
  .. > "$OUT/libriscv-cmake.log" 2>&1
make gx_rv -j"$(nproc)" > "$OUT/libriscv-make.log" 2>&1

# Do NOT rename these. The generated .mjs hardcodes
# findWasmBinary() -> new URL("gx_rv.wasm", import.meta.url).
cp "$B/gx_rv.mjs" "$B/gx_rv.wasm" "$OUT/"
EMV=$(emcc --version | head -1)
echo "{\"emulator\":\"libriscv\",\"commit\":\"$LIBRISCV_COMMIT\",\"license\":\"BSD-3-Clause\",\"mem\":\"wasm32\",\"ext_c\":\"ON (mandatory)\",\"emcc\":\"$EMV\"}" > "$OUT/libriscv-manifest.json"
echo "## gx_rv.wasm $(stat -c%s "$OUT/gx_rv.wasm") bytes"
test "$(stat -c%s "$OUT/gx_rv.wasm")" -gt 100000
