#!/usr/bin/env bash
# build.sh <out-dir> -- build the wrapper through libriscv's own CMake.
set -uo pipefail
OUT="${1:?}"; mkdir -p "$OUT"
HERE="$(cd "$(dirname "$0")" && pwd)"
D="$HOME/rv-libriscv"
[ -d "$D" ] || git clone --depth 1 https://github.com/libriscv/libriscv.git "$D" >/dev/null 2>&1
echo "## libriscv $(git -C "$D" rev-parse --short HEAD)"
. "$EMSDK/emsdk_env.sh" >/dev/null 2>&1 || true

# Round 2 hand-rolled emcc -I lib/ and died on a MISSING libriscv_settings.h --
# that header is GENERATED by their CMake. Their examples/wasm builds fine, so
# use their build system instead of reinventing it.
cp "$HERE/CMakeLists.txt" "$HERE/gx_rv.cpp" "$OUT/"
cd "$OUT"
if ! emcmake cmake -B build -DLIBRISCV_DIR="$D" . > "$OUT/cmake.log" 2>&1; then
  echo "## CMAKE FAILED"; grep -iE "error|CMake Error" "$OUT/cmake.log" | head -10 | sed 's/^/   /'; exit 1
fi
# Print the actual compile line. Round 3 shipped without -fexceptions and the
# only symptom was a wasm table error at runtime -- a flag you cannot see is a
# flag you cannot trust.
emcmake cmake -B build -DLIBRISCV_DIR="$D" -DCMAKE_VERBOSE_MAKEFILE=ON . >> "$OUT/cmake.log" 2>&1 || true
if ! cmake --build build -j"$(nproc)" > "$OUT/build.log" 2>&1; then
  echo "## BUILD FAILED"; grep -iE "error" "$OUT/build.log" | head -12 | sed 's/^/   /'; exit 1
fi
find build -name "gx_rv.*" -exec cp {} "$OUT/" \; 2>/dev/null
ls -la "$OUT"/gx_rv.* 2>/dev/null | awk '{print "   "$5, $9}'
grep -o "\-fexceptions" "$OUT/build.log" | head -1 | sed "s/^/## compile carries: /" || echo "## WARNING: -fexceptions not seen in the build log"
test -f "$OUT/gx_rv.wasm" && echo "## WRAPPER BUILT" || { echo "## no gx_rv.wasm produced"; exit 1; }
